<a href="https://colab.research.google.com/github/Rudhra-06/Rudhrashini-Codeboosters-Internship-2026/blob/main/Day_01_Data_Engineering_GitHub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

print("Libraries imported successfully")

Libraries imported successfully

In [4]:
df=pd.read_csv('student_performance.csv')

print("Dataset loaded successfully")

Dataset loaded successfully

In [5]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [12]:
print("Number of rows & columns : ",df.shape)
# prints rows and columns

print("number of students(rows) : ",df.shape[0])
# 0 -> rows

print("number of columns : ",df.shape[1])
# 1 -> columns

Number of rows & columns :  (30, 13)
number of students(rows) :  30
number of columns :  13

columns is an attribute that give sus all column names.
.tolist() converts it from a pandas index objext into regular Python list

In [15]:
print("Columns in the dataset : ")
print(df.columns.tolist())

print(" ")

df.columns.tolist()

Columns in the dataset :
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

A list in Python is a collection of items inside square Brackets[].
This shows us all 13 column names

In [20]:
print("Data Types of Columns :\n", df.dtypes)

Data Types of Columns :
 student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In pandas, Strings are objects

In [18]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [22]:
print("Missing values in each column :")
print(df.isnull().sum())
print("\nTotal missing values : ",df.isnull().sum().sum())

Missing values in each column :
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

Total missing values :  0

isnull() finds the rows that are empty in a column and the sum() finds the number of rows per column.
So, the result is missing values in each column.

In [28]:
print("Student names : ")
print(df['name'])
print("\nDepartments : ")
print(df['department'].unique())

Student names :
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

Departments :
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [29]:
print("Number of students per department : ")
print(df['department'].value_counts())

Number of students per department :
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

value_counts() counts the number of times each unique value appears

In [31]:
cs_students=df[df['department']=='Computer Science']

print(f"Number of Computer Science Students : {len(cs_students)}")

print("\nComputer Science Students details : ")
print(cs_students[['name','math_score','programming_score','science_score','english_score','attendance_percentage']])

Number of Computer Science Students : 13

Computer Science Students details :
              name  math_score  programming_score  science_score  \
0     Aarav Sharma          85                 91             78
1      Priya Patel          76                 79             82
4       Arjun Nair          92                 95             88
7      Divya Singh          88                 93             91
9       Ananya Das          95                 97             89
12      Suresh Rao          83                 88             86
14     Ajay Tiwari          71                 76             69
17  Swati Kulkarni          90                 92             87
19    Nisha Kapoor          79                 83             84
21     Tanvi Mehta          93                 96             90
24       Amit Bose          86                 89             82
26   Gaurav Shukla          84                 87             79
29  Akanksha Yadav          91                 94             93

    english_score  attendance_percentage
0              72                     92
1              88                     87
4              81                     90
7              84                     96
9              90                     98
12             77                     88
14             64                     75
17             85                     94
19             81                     89
21             88                     97
24             79                     91
26             75                     87
29             87                     95

In [32]:
high_attendance=df[df['attendance_percentage']>90]

print(f"Number of students with attendance above 90% : {len(high_attendance)}")

print(high_attendance[['name','department','attendance_percentage']])

Number of students with attendance above 90% : 10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [35]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}%")

Top student :
Name : Ananya Das
Department : Computer Science
Total Score : 371
Attendance : 98%

loc -> locates the row by index

In [36]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)

print("Average total score by department : ")
print(dept_avg)

Average total score by department :
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [38]:
df_sorted=df.sort_values(by='total_score',ascending=False)

print("Top 10 students by total score : ")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

Top 10 students by total score :
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

# PRACTICE QUESTIONS

Try solving these on your own.
1. How many students are from the Electronics department?
2. What is the average attendance of female students?
3. Who is the student with the lowest programming score?
4. How many students scored above 80 in math?
5. What is the avg total_score for students with attendance above 90%?

In [42]:

electronics_students = df[df['department'] == 'Electronics']

print("Number of Electronics students:", len(electronics_students))

Number of Electronics students: 6

In [47]:

female_students = df[df['gender'] == 'Female']

average_attendance = female_students['attendance_percentage'].mean()

print("Average attendance of female students:", average_attendance)

Average attendance of female students: 88.53333333333333

In [44]:

lowest_programming = df[df['programming_score'] == df['programming_score'].min()]

print(lowest_programming[['name', 'programming_score']])

            name  programming_score
16  Manoj Pandey                 38

In [45]:

above_80_math = df[df['math_score'] > 80]

print("Number of students scoring above 80 in math:", len(above_80_math))

Number of students scoring above 80 in math: 11

In [46]:

above_90_attendance = df[df['attendance_percentage'] > 90]

average_total_score = above_90_attendance['total_score'].mean()

print("Average total score for students with attendance above 90%:", average_total_score)

Average total score for students with attendance above 90%: 335.8

# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings

In [49]:
print("=" * 50)
print("      STUDENT PERFORMANCE EXPLORER")
print("=" * 50)

==================================================
      STUDENT PERFORMANCE EXPLORER
==================================================

In [50]:
print("\nDATASET OVERVIEW")
print("-" * 30)

print(f"Total number of students : {df.shape[0]}")
print(f"Total number of columns  : {df.shape[1]}")
print(f"Unique departments       : {df['department'].nunique()}")

DATASET OVERVIEW
------------------------------
Total number of students : 30
Total number of columns  : 14
Unique departments       : 4

In [51]:
print("\nDEPARTMENT-WISE ANALYSIS")
print("-" * 30)

dept_count = df['department'].value_counts()

for dept, count in dept_count.items():
    print(f"{dept} : {count} students")

DEPARTMENT-WISE ANALYSIS
------------------------------
Computer Science : 13 students
Electronics : 6 students
Mechanical : 6 students
Civil : 5 students

In [52]:
print("\nSCORE ANALYSIS")
print("-" * 30)

print(f"Highest Math Score            : {df['math_score'].max()}")
print(f"Lowest Math Score             : {df['math_score'].min()}")
print(f"Average Programming Score     : {df['programming_score'].mean():.2f}")
print(f"Average Attendance Percentage : {df['attendance_percentage'].mean():.2f}")

SCORE ANALYSIS
------------------------------
Highest Math Score            : 95
Lowest Math Score             : 56
Average Programming Score     : 67.60
Average Attendance Percentage : 84.50

In [53]:
print("\nGENDER-WISE ANALYSIS")
print("-" * 30)

gender_avg = df.groupby('gender')['total_score'].mean().round(2)

for gender, avg in gender_avg.items():
    print(f"{gender} : {avg}")

GENDER-WISE ANALYSIS
------------------------------
Female : 310.67
Male : 280.67

In [54]:
print("\nTOP 5 STUDENTS BASED ON TOTAL SCORE")
print("-" * 50)

top_students = df.sort_values(by='total_score', ascending=False).head(5)

for index, row in top_students.iterrows():
    print(f"Name : {row['name']}")
    print(f"Department : {row['department']}")
    print(f"Total Score : {row['total_score']}")
    print("-" * 30)

TOP 5 STUDENTS BASED ON TOTAL SCORE
--------------------------------------------------
Name : Ananya Das
Department : Computer Science
Total Score : 371
------------------------------
Name : Tanvi Mehta
Department : Computer Science
Total Score : 367
------------------------------
Name : Akanksha Yadav
Department : Computer Science
Total Score : 365
------------------------------
Name : Arjun Nair
Department : Computer Science
Total Score : 356
------------------------------
Name : Divya Singh
Department : Computer Science
Total Score : 356
------------------------------

In [55]:
print("\nSTUDENTS WITH ATTENDANCE BELOW 75%")
print("-" * 40)

low_attendance = df[df['attendance_percentage'] < 75]

if len(low_attendance) > 0:

    for index, row in low_attendance.iterrows():
        print(f"Name : {row['name']}")
        print(f"Department : {row['department']}")
        print(f"Attendance Percentage : {row['attendance_percentage']}%")
        print("-" * 30)

else:
    print("All students have attendance above 75%")

STUDENTS WITH ATTENDANCE BELOW 75%
----------------------------------------
Name : Meera Joshi
Department : Electronics
Attendance Percentage : 72%
------------------------------
Name : Rahul Mishra
Department : Mechanical
Attendance Percentage : 68%
------------------------------
Name : Manoj Pandey
Department : Civil
Attendance Percentage : 65%
------------------------------
Name : Harish Pillai
Department : Electronics
Attendance Percentage : 74%
------------------------------
Name : Sanjay Dubey
Department : Civil
Attendance Percentage : 70%
------------------------------
Name : Sunita Pillai
Department : Civil
Attendance Percentage : 73%
------------------------------

In [58]:
#1. PROJECT TITLE


print("=" * 50)
print("      STUDENT PERFORMANCE EXPLORER")
print("=" * 50)


# 2. DATASET OVERVIEW


print("\nDATASET OVERVIEW")
print("-" * 30)

print(f"Total number of students : {df.shape[0]}")
print(f"Total number of columns  : {df.shape[1]}")
print(f"Unique departments       : {df['department'].nunique()}")


# 3. DEPARTMENT-WISE ANALYSIS


print("\nDEPARTMENT-WISE ANALYSIS")
print("-" * 30)

dept_count = df['department'].value_counts()

for dept, count in dept_count.items():
    print(f"{dept} : {count} students")


# 4. SCORE ANALYSIS


print("\nSCORE ANALYSIS")
print("-" * 30)

print(f"Highest Math Score            : {df['math_score'].max()}")
print(f"Lowest Math Score             : {df['math_score'].min()}")
print(f"Average Programming Score     : {df['programming_score'].mean():.2f}")
print(f"Average Attendance Percentage : {df['attendance_percentage'].mean():.2f}")


# 5. GENDER-WISE ANALYSIS


print("\nGENDER-WISE ANALYSIS")
print("-" * 30)

gender_avg = df.groupby('gender')['total_score'].mean().round(2)

for gender, avg in gender_avg.items():
    print(f"{gender} : {avg}")


# 6. TOP 5 STUDENTS


print("\nTOP 5 STUDENTS BASED ON TOTAL SCORE")
print("-" * 50)

top_students = df.sort_values(by='total_score', ascending=False).head(5)

for index, row in top_students.iterrows():
    print(f"Name : {row['name']}")
    print(f"Department : {row['department']}")
    print(f"Total Score : {row['total_score']}")
    print("-" * 30)


# 7. ATTENDANCE ANALYSIS


print("\nSTUDENTS WITH ATTENDANCE BELOW 75%")
print("-" * 40)

low_attendance = df[df['attendance_percentage'] < 75]

if len(low_attendance) > 0:

    for index, row in low_attendance.iterrows():
        print(f"Name : {row['name']}")
        print(f"Department : {row['department']}")
        print(f"Attendance Percentage : {row['attendance_percentage']}%")
        print("-" * 30)

else:
    print("All students have attendance above 75%")

==================================================
      STUDENT PERFORMANCE EXPLORER
==================================================

DATASET OVERVIEW
------------------------------
Total number of students : 30
Total number of columns  : 14
Unique departments       : 4

DEPARTMENT-WISE ANALYSIS
------------------------------
Computer Science : 13 students
Electronics : 6 students
Mechanical : 6 students
Civil : 5 students

SCORE ANALYSIS
------------------------------
Highest Math Score            : 95
Lowest Math Score             : 56
Average Programming Score     : 67.60
Average Attendance Percentage : 84.50

GENDER-WISE ANALYSIS
------------------------------
Female : 310.67
Male : 280.67

TOP 5 STUDENTS BASED ON TOTAL SCORE
--------------------------------------------------
Name : Ananya Das
Department : Computer Science
Total Score : 371
------------------------------
Name : Tanvi Mehta
Department : Computer Science
Total Score : 367
------------------------------
Name : Akanksha Yadav
Department : Computer Science
Total Score : 365
------------------------------
Name : Arjun Nair
Department : Computer Science
Total Score : 356
------------------------------
Name : Divya Singh
Department : Computer Science
Total Score : 356
------------------------------

STUDENTS WITH ATTENDANCE BELOW 75%
----------------------------------------
Name : Meera Joshi
Department : Electronics
Attendance Percentage : 72%
------------------------------
Name : Rahul Mishra
Department : Mechanical
Attendance Percentage : 68%
------------------------------
Name : Manoj Pandey
Department : Civil
Attendance Percentage : 65%
------------------------------
Name : Harish Pillai
Department : Electronics
Attendance Percentage : 74%
------------------------------
Name : Sanjay Dubey
Department : Civil
Attendance Percentage : 70%
------------------------------
Name : Sunita Pillai
Department : Civil
Attendance Percentage : 73%
------------------------------